[theme]
# shades of purple color theme
primaryColor="#fad000"
backgroundColor="#28284e"
secondaryBackgroundColor="#222145"
textColor="#ffffff"
font="sans serif"

# # this is needed for local development with docker
# [server]
# # if you don't want to start the default browser:
# headless = true
# # you will need this for local development:
# runOnSave = true
# # you will need this if running docker on windows host:
# fileWatcherType = "poll"
